# Generated by Django 5.2.3 on 2025-06-11 21:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentadmission',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='studentadmission',
            name='parent_name',
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='apaar_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='category',
            field=models.CharField(choices=[('GEN', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], default='GEN', max_length=10),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='father_profession',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='mother_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='religion',
            field=models.CharField(blank=True, default='Hindu', max_length=50),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='whatsapp_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
