# Generated by Django 5.2.3 on 2025-06-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_remove_studentadmission_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadmission',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='apaar_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
