# Generated by Django 5.2.3 on 2025-06-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_alter_studentadmission_aadhar_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadmission',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='father_profession',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='mother_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
