# Generated by Django 5.2.3 on 2025-06-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_alter_studentadmission_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadmission',
            name='religion',
            field=models.CharField(choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Christian', 'Christian'), ('Sikh', 'Sikh'), ('Other', 'Other')], default='Hindu', max_length=50),
        ),
    ]
