# Generated by Django 5.2.3 on 2025-06-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_alter_studentadmission_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadmission',
            name='category',
            field=models.CharField(choices=[('GEN', 'GEN'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], default='GEN', max_length=10),
        ),
    ]
