# Generated by Django 5.2.3 on 2025-06-13 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0005_alter_studentadmission_religion'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=True, help_text='Checked = monthly recurring')),
                ('account_head', models.ForeignKey(help_text='Accounting ledger this fee type is linked to', on_delete=django.db.models.deletion.PROTECT, related_name='fee_types', to='transactions.accounthead')),
            ],
        ),
        migrations.CreateModel(
            name='StudentOpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('opening_advance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission.studentadmission')),
            ],
        ),
    ]
