# Generated by Django 5.2.3 on 2025-06-13 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_alter_studentadmission_religion'),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.feetype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_plans', to='admission.studentadmission')),
            ],
            options={
                'unique_together': {('student', 'fee_type')},
            },
        ),
    ]
