# Generated by Django 5.2.3 on 2025-06-13 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_alter_studentadmission_religion'),
        ('fees', '0002_studentfeeplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeeDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Use 1st of the month for uniformity, e.g. 2025-07-01')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_posted', models.BooleanField(default=False)),
                ('carry_forward', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.feetype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.studentadmission')),
            ],
            options={
                'unique_together': {('student', 'fee_type', 'month')},
            },
        ),
    ]
