# Generated by Django 5.2.3 on 2025-06-13 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_alter_studentadmission_religion'),
        ('fees', '0003_studentfeedue'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('month', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.studentadmission')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeePaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.feetype')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='fees.studentfeepayment')),
            ],
        ),
    ]
