# Generated by Django 5.2.3 on 2025-06-13 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_alter_studentadmission_religion'),
        ('fees', '0004_studentfeepayment_studentfeepaymentdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAdvanceBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission.studentadmission')),
            ],
        ),
    ]
