# Generated by Django 5.2.3 on 2025-06-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_studentadvancebalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeepayment',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Online/Bank')], default='CASH', max_length=10),
        ),
    ]
