# Generated by Django 5.2.3 on 2025-06-17 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_studentfeepayment_payment_mode'),
        ('transactions', '0003_accounthead_school_transaction_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feetype',
            name='is_recurring',
        ),
        migrations.AlterField(
            model_name='feetype',
            name='account_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_types', to='transactions.accounthead'),
        ),
    ]
