# Generated by Django 5.2.3 on 2025-06-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0007_remove_feetype_is_recurring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeedue',
            name='original_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
