# Generated by Django 5.2.3 on 2025-06-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0008_studentfeedue_original_due'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentfeepayment',
            old_name='month',
            new_name='payment_date',
        ),
        migrations.AlterField(
            model_name='studentfeepayment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
