# Generated by Django 5.2.3 on 2025-06-13 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('transactions', '0002_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accounthead',
            name='school',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='core.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='voucher_type',
            field=models.CharField(blank=True, choices=[('payment', 'Payment'), ('receipt', 'Receipt'), ('journal', 'Journal'), ('contra', 'Contra')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='school',
            field=models.ForeignKey(default='kalawati', on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
    ]
