# Generated by Django 5.2.3 on 2025-07-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_accounthead_school_transaction_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
