# Generated by Django 5.2.3 on 2025-07-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
