# Generated by Django 5.2.3 on 2025-07-09 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_school_short_name'),
        ('transactions', '0005_transactioncounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolTransactionCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
        ),
        migrations.DeleteModel(
            name='TransactionCounter',
        ),
    ]
