# Generated by Django 5.2.3 on 2025-07-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_school_short_name'),
        ('transactions', '0006_schooltransactioncounter_delete_transactioncounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('school', 'transaction_id')},
        ),
    ]
